version: '3'
services:
  backend-module-container:
    container_name: backend-module-container
    restart: always
    build: ./backend-module
    ports:
      - '9001:3000'
    links:
      - mongo-module-container
    env_file:
      - ./backend-module/.env
    volumes:
      - ./backend-module:/app
  mongo-module-container:
    container_name: mongo-module-container
    image: mongo:4.0.4
    ports:
      - '27017:27017'
    volumes:
      - db-volume:/data/db

volumes:
  db-volume:
